# -*- coding: utf-8 -*-
"""earth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEs7-EFVcpsT_wK87MrTmyMPeTOvDtsp
"""

earth/                          # Top-level package
      __init__.py               # Initialize the earth package
      asia/                     # Subpackage for file asia
              __init__.py
              japan.py
              mongolia.py       # A module under a subpackage
              pakistan.py
              taiwan.py
              ...
      europe/                   # Subpackage for file europe
              __init__.py
              germany.py        # A module under a subpackage
              england.py
              turkey.py
              kosovo.py
              ...
      america/                  # Subpackage for file america
              __init__.py
              canada.py
              ustates.py
              mexico.py
              peru.py