# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16cFRFD2n0Br5uZF75CRKx7cneE5AyKBg
"""

print('hello')
def my_func1(x):
  return print(x**2)

my_func1(3)

def my_func2(y):
  return print(*y)
my_func2("clarusway")