# -*- coding: utf-8 -*-
"""my_first

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lqxM6MDmdL0sqX4avsV6WOMBRUkQcc6
"""

"""
my_first modülümün docstringidir.
Test amacli 2 adet fonksiyon icerir.
"""
def func1(ad="Python"):
  return f"Ooo, {ad} dilini ögreniyorsun"

def func2():
  return f"ben 2. fonksiyonum"

pi_sayisi = 3.14156