# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhLIOqfYHFoyR9GYUMb96Mp5eU0tsacE
"""

!python3 --version # python major minor

print("hello world!")





print(3.14) # sayisal tipte veri

print(''''we shold have enough time for family"''')

print("1. satir")
print()
print("3.satir")

print()
print("")

print(''''\)

x = 5
print("x in degeri", x)



print('''''')

print('3.14')
# string text tipte veri

help(print)

import this